openapi: 3.0.0
x-medialake-nodeId: pre_signed_url
x-node-type: utility
info:
    title: AWS S3 Pre-Signed URL
    version: .1
    description: AWS S3 Pre-Signed URL

security:
  - awsIam: []


externalDocumentation:
  url: nodes/utility/pre_signed_url.zip
  description: AWS S3 Pre-Signed URL ZIP location

paths:
  /pre_signed_url:
    get:
      summary: Generate Pre-Signed URL
      operationId: generate_pre_signed_url