openapi: 3.0.0
x-medialake-nodeId: flow_wait
x-node-type: utility
x-node-deployment-type: step_function_step
x-node-integration-type: step_function
x-node-input-type: [any]
x-node-output-type: [any]

info:
    title: Wait
    version: 1.0
    description: Wait for a certain amount of time

security:
  - awsIam: []

tags:
  - name: Flow

externalDocumentation:
  url: wait
  description: AWS Step Function Wait step

paths:
  /wait:
    post:
      summary: Wait for a certain amount of time
      operationId: wait_for_time